
GET http://localhost:5138/games

###
GET http://localhost:5138/games/1

###
GET http://localhost:5138/games/8


####
POST http://localhost:5138/games
Content-Type: application/json

{
    "name": "God of War",
    "genre": "Action-adventure",
    "price": 49.99,
    "releaseDate": "2018-04-20"
}
###
PUT http://localhost:5138/games/1 
Content-Type: application/json

{
    "name": "The Legend of Zelda: Breath of the Wild",
    "genre": "Action-adventure",
    "price": 9.99,
    "releaseDate": "2017-03-03"
}